language: python
sudo: false
python:
- '2.7'
install:
- npm install npm@latest -g
- npm install jscs -g
- npm install jshint -g
- npm install
- jscs -V
- jshint -v
- pip install "GitPython>=0.2.0-beta1" --use-mirrors
- mkdir -p vendors
script:
- ./skulpt.py dist
- jshint src/*.js
- jscs src/*.js
after_script:
- ./dist-update.sh