language: python
sudo: false
python:
- '2.7'
install:
- nvm install 'lts/*'
- nvm use 'lts/*'
- npm install npm@latest -g
- npm install
- pip install "GitPython>=0.2.0-beta1"
- mkdir -p vendors
script:
- npm run build-min
- npm test
after_script:
- ./dist-update.sh